#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# cd thermophysicalModels
# ./Allwmake
# cd ..

wmake -j $targetType basic
wmake -j $targetType sampling
wmake -j $targetType fvOptions
wmake -j $targetType intermediate
wmake -j $targetType turbulence
wmake -j $targetType coalCombustion
wmake -j $targetType solidParticle


wmake -j $targetType

#------------------------------------------------------------------------------
