#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso basic
wclean libso fvOptions
wclean libso sampling
wclean libso solidParticle
wclean libso coalCombustion
wclean libso intermediate
wclean libso turbulence
#------------------------------------------------------------------------------
